### PR TITLE
My first commit

### PR DESCRIPTION
**Pull request by Astha-Bhushan**
I have written a snippet for preprocessing text for building models using NLP. It consists of tokenizing, removing stopwords, and providing the importance of each word in the text.
#hacktoberfest

### CODE REVIEW

**Comment by pawarashish564** [comment]
It's good that you added NLP snippet. But Why are removed all the other snippets in collection.

**Comment by Astha-Bhushan** [comment]
okay I will include all other snippets also .

**Comment by Astha-Bhushan** [comment]
I am generating another pull request with other snippets.Is it okay?

**Comment by pawarashish564** [comment]
Fine create another one. Do it neat.

**Pull request closed without merging**
